---
    - hosts: all
      gather_facts: yes
      vars_files:
        - /etc/ansible/vars/default.yml
        - /etc/ansible/vars/default1.yml
      tasks:
        - name: install Lamp
          ansible.builtin.package:
            name: 
             - httpd
             - mariadb-server
             - php
            state: latest
          when: ansible_facts['distribution']=="CentOS"

        - name: install Lamp in ubuntu
          
          ansible.builtin.package:
            name:
              - apache2
              - mariadb-server
              - php
            state: latest
          when: ansible_facts['distribution']=="Ubuntu"

        - name: apache_up
          ansible.builtin.service:
            name: httpd
            state: started

        - name: datadase_up
          ansible.builtin.service:
            name: mariadb
            state: started

        # - name: apache_up
        #   ansible.builtin.service:
        #     name: apache2
        #     state: started

        - name: Create document root
          file:
            path: "/var/www/html"
            state: directory
            mode: '0755'
        - name: Copy index test page
          template:
            src: "files/index.html.j2"
            dest: "/var/www/html/index.html"
        - name: Set up Apache virtuahHost
          template:
            src: "/etc/ansible/files/apache.conf.j2"
            dest: "/var/www/html"

        - name: apache_up
          ansible.builtin.service:
            name: httpd
            state: restarted

        - name: Install PHP Extensions
          ansible.builtin.yum:
            name: "{{ item }}"
            state: latest
          loop: "{{ php_modules }}"
        - name: Set the mysqluser password
          mysql_user:
            name: "{{ mysql_user }}"
            priv: '*.*:ALL'
            password: "{{ mysql_password }}"
